# Generated by Django 2.2.1 on 2019-05-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='image',
        ),
    ]
