# Generated by Django 2.2.1 on 2019-05-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_auto_20190507_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='image',
            new_name='file',
        ),
    ]
